### ISSUE TITLE
Extend place-object with more location data

### ISSUE THREAD

**Issue by thoughtgap** [nathangrigg/dayone_export#24]
Can we get this? Thanks...

I am editing this comment to phrase a more specific feature request. It would be nice to extend the place-element with more information from the DayOne-entry (if available). The Location information in a DayOne-entry look like this:

    <key>Location</key>
    <dict>
    	<key>Administrative Area</key>
    	<string>NY</string>
    	<key>Country</key>
    	<string>USA</string>
    	<key>Foursquare ID</key>
    	<string>49b7ed6df964a52030531fe3</string>
    	<key>Latitude</key>
    	<real>40.756489872673846</real>
    	<key>Locality</key>
    	<string>New York City</string>
    	<key>Longitude</key>
    	<real>-73.986268043518066</real>
    	<key>Place Name</key>
    	<string>Times Square</string>
    </dict>

It would be nice to have these fields available in the place-object (or a separate location object). This way it would be possible to include a link to the exact coordinates, embed a map in the html-file and much more.
Unfortunately I have no perl experience. I will try to dig a bit into the code but then I need to figure out how to run my modified code. We'll see...

**Comment by thoughtgap** [comment]
I updated this issue with a more detailed feature request.

**Comment by nathangrigg** [comment]
These are all accessible in the Entry object.

Simply use entry['Latitude'] or entry['Longitude'] or entry['Foursquare ID']. In other words, all children of the 'Location' key are treated as if they are top-level keys.

The 'place' function is just a convenience to display 'Times Square, New York City, NY, USA'.
